apiVersion: apps/v1
kind: Deployment
metadata:
  name: sliit-2022-test
spec:
  selector:
    matchLabels:
      app: sliit-2022-test
  template:
    metadata:
      labels:
        app: sliit-2022-test
    spec:
      containers:
      - name: sliit-2022-test 
        image: prasad44/sliit-2022-test
        resources: 
          limits:
            memory: "521Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
      