apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: test-sliit
  name: test-sliit
  namespace: default
  spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-sliit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-sliit
    spec:
      containers:
      - image: prasad44/sliit-2022
        imagePullPolicy: Always
        name: sliit-2022
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          -containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      sheduleName: default-sheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30